-- MySQL Script generated by MySQL Workbench
-- Tue Aug 19 21:39:17 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema BIA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BIA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BIA` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `BIA` ;

-- -----------------------------------------------------
-- Table `BIA`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BIA`.`companies` (
  `company_id` VARCHAR(255) NOT NULL,
  `name` TEXT NULL DEFAULT NULL,
  `tax_payer` TEXT NULL DEFAULT NULL,
  `sic_agpe` TEXT NULL DEFAULT NULL,
  `solar_starts_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`company_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BIA`.`contracts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BIA`.`contracts` (
  `contract_id` VARCHAR(255) NOT NULL,
  `company_id` VARCHAR(255) NULL DEFAULT NULL,
  `start_date` DATETIME NULL DEFAULT NULL,
  `end_date` DATETIME NULL DEFAULT NULL,
  `market_type` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`contract_id`),
  CONSTRAINT `company_id`
    FOREIGN KEY (`company_id`)
    REFERENCES `BIA`.`companies` (`company_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `company_id_idx` ON `BIA`.`contracts` (`company_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `BIA`.`bills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BIA`.`bills` (
  `id` VARCHAR(255) NOT NULL,
  `contract_id` VARCHAR(255) NULL DEFAULT NULL,
  `period` TEXT NULL DEFAULT NULL,
  `cuttoff_date` DATETIME NULL DEFAULT NULL,
  `total` DOUBLE NULL DEFAULT NULL,
  `status` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_bills_contract_id`
    FOREIGN KEY (`contract_id`)
    REFERENCES `BIA`.`contracts` (`contract_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `contract_id_idx` ON `BIA`.`bills` (`contract_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `BIA`.`bill_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BIA`.`bill_details` (
  `id` VARCHAR(255) NOT NULL,
  `bill_id` VARCHAR(255) NULL DEFAULT NULL,
  `line_type` TEXT NULL DEFAULT NULL,
  `amount` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_bill_details_bill_id`
    FOREIGN KEY (`bill_id`)
    REFERENCES `BIA`.`bills` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `bill_id_idx` ON `BIA`.`bill_details` (`bill_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `BIA`.`consumptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BIA`.`consumptions` (
  `id` VARCHAR(255) NOT NULL,
  `contract_id` VARCHAR(255) NULL DEFAULT NULL,
  `meter_id` TEXT NULL DEFAULT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  `hour` INT NULL DEFAULT NULL,
  `kwh` DOUBLE NULL DEFAULT NULL,
  `deleted_at` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `contract_id`
    FOREIGN KEY (`contract_id`)
    REFERENCES `BIA`.`contracts` (`contract_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `contract_id_idx` ON `BIA`.`consumptions` (`contract_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `BIA`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BIA`.`payments` (
  `id` VARCHAR(255) NOT NULL,
  `bill_id` VARCHAR(255) NULL DEFAULT NULL,
  `paid_at` DATETIME NULL DEFAULT NULL,
  `method` TEXT NULL DEFAULT NULL,
  `token` TEXT NULL DEFAULT NULL,
  `status` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `bill_id`
    FOREIGN KEY (`bill_id`)
    REFERENCES `BIA`.`bills` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `bills_id_idx` ON `BIA`.`payments` (`bill_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
